spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5434/demo
    username: demo_tarou
    password: MBDSLNBSDBDS532FBS0SGE
    driver-class-name: org.postgresql.Driver
server:
  port: 8081
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true