spring:
  application:
    name: batch
  datasource:
    url: jdbc:postgresql://localhost:5434/demo
    username: demo_tarou
    password: MBDSLNBSDBDS532FBS0SGE
    driver-class-name: org.postgresql.Driver